export const exerciseClasses = {
  section: 'rensyuBlock',
  content: 'rensyuNaiyou',
  hint: 'rensyuHint',
  hintContent: 'rensyuHintNaiyou',
  solution: 'rensyuKaitou',
  solutionContent: 'rensyuKaitouNaiyou',
  quickCheck: 'rensyuQuickCheck',
  quickCheckTitle: 'rensyuQuickCheckTitle',
  taskHeader: 'rensyuTaskHeader',
  taskHeaderIcon: 'rensyuTaskHeaderIcon',
  summary: 'rensyuSummary',
  summaryLabel: 'rensyuSummaryLabel',
  summaryIcon: 'rensyuSummaryIcon',
  summaryChevron: 'rensyuSummaryChevron',
  blankWrap: 'rensyuBlankWrap',
  blankInput: 'rensyuBlankInput',
  blankBadge: 'rensyuBlankBadge',
  blankTag: 'rensyuBlankTag',
  blankHighlight: 'rensyuBlankHighlight',
  blankAnswerList: 'rensyuBlankAnswerList',
  blankAnswerItem: 'rensyuBlankAnswerItem',
} as const;
